include                 theme.conf

font_family             JetBrainsMono Nerd Font Mono
font_size               18.0
window_padding_width    5
italic_font             auto
bold_font               auto
bold_italic_font        auto
background_opacity      1
copy_on_select          no
scrollbar               never
confirm_os_window_close 0
cursor_trail            1
